services:
  - type: web
    name: fit-app-api
    env: docker
    dockerfilePath: apps/api/Dockerfile
    repo: https://github.com/Duver0/fit-app
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_qlvf5X1LUmEg@ep-young-moon-awpk5tqy-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: DIRECT_URL
        value: postgresql://neondb_owner:npg_qlvf5X1LUmEg@ep-young-moon-awpk5tqy.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: REDIS_HOST
        value: discovery-swim-ultraclean-41976.db.redis.io
      - key: REDIS_PORT
        value: "12571"
      - key: REDIS_PASSWORD
        value: UIdocmTtLMAgTpbwzCfslJuXdIDRpDuO
      - key: JWT_SECRET
        value: Ne9vfL3AJk0mlZQOJ+Bv9Qs/TAHpNzipP7ao0B2TMVM=
      - key: CORS_ORIGIN
        value: https://duver0.github.io
      - key: NODE_ENV
        value: production
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: APP_URL
        value: https://fit-app-api.onrender.com
      # PORT is auto-set by Render
